// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ_tWCUKR-gmqgA5NGzSfs5IjmJG2hBu8',
    appId: '1:687310192425:web:c8a011efea6b2fced4c138',
    messagingSenderId: '687310192425',
    projectId: 'switchit-f3d74',
    authDomain: 'switchit-f3d74.firebaseapp.com',
    storageBucket: 'switchit-f3d74.appspot.com',
    measurementId: 'G-KBL9H5QXS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVr0r7ZjizrI0_eXE9KcTiRM8bxJkI3UM',
    appId: '1:687310192425:android:ac6fed0ab6c4a25cd4c138',
    messagingSenderId: '687310192425',
    projectId: 'switchit-f3d74',
    storageBucket: 'switchit-f3d74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiaUbnAgibWKURHTtR7QS1rnqjuHKF3h0',
    appId: '1:687310192425:ios:d1f02be51174ee27d4c138',
    messagingSenderId: '687310192425',
    projectId: 'switchit-f3d74',
    storageBucket: 'switchit-f3d74.appspot.com',
    iosClientId: '687310192425-276b8r77u87aqo0krbakgq7os0ej73tg.apps.googleusercontent.com',
    iosBundleId: 'pt.up.switchit',
  );
}
