include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    avoid_type_to_string: true
    empty_statements: true
    no_logic_in_create_state: true
    unnecessary_statements: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: false
    avoid_bool_literals_in_conditional_expressions: true
    avoid_print: true
# https://dart.dev/guides/language/analysis-options
# https://dart.dev/tools/linter-rules
